# Generated by Django 4.0.5 on 2022-06-22 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(editable=False, max_length=30)),
                ('recipient', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=40, null=True)),
                ('message', models.TextField(null=True)),
                ('date_created', models.DateTimeField(editable=False)),
                ('msg_read', models.BooleanField(default=False, editable=False)),
                ('owner', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
