# Generated by Django 4.0.5 on 2022-06-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg_sys_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.CharField(max_length=30, verbose_name='recipient(username)'),
        ),
    ]
